#!/usr/bin/env python3
"""
scripts/gen_sos_coeffs.py — Butterworth SOS 계수 생성기 (개발 PC 전용)

펌웨어 tools/gen_sos.py 와 동일한 계수를 생성한다.
RPi/Docker 에서 실행하는 용도가 아님 — scipy 필요.

Usage:
    python scripts/gen_sos_coeffs.py            # stdout 출력 (확인용)
    python scripts/gen_sos_coeffs.py out.h      # 파일 직접 쓰기 (권장)

출력 결과를 펌웨어 src/biquad_coeffs.h 에 붙여 넣고 pio run 으로 재빌드.
대역폭을 변경하면 이 스크립트를 재실행하고 펌웨어도 같이 갱신할 것.
"""

import sys

try:
    from scipy.signal import butter
    import numpy as np
except ImportError:
    sys.exit("ERROR: scipy and numpy required — pip install scipy numpy")

# ─── Parameters (config.h 와 반드시 일치) ─────────────────────────────────────
FS         = 100          # Hz  (CSI_FS)
ORDER      = 4            # Butterworth prototype order → 4 SOS sections (bandpass)
RESP_BAND  = [0.1, 0.6]  # Hz  (호흡)
HEART_BAND = [0.8, 3.0]  # Hz  (심박)


def compute_sos(band, fs, order):
    nyq = fs / 2.0
    sos = butter(order, [b / nyq for b in band], btype="bandpass", output="sos")
    assert np.allclose(sos[:, 3], 1.0), "a0 normalisation violated"
    return sos


def fmt_array(name, desc, sos):
    n = sos.shape[0]
    lines = []
    lines.append(f"/* {desc} - [b0,b1,b2, 1,a1,a2] per section */")
    lines.append(f"static const float {name}[SOS_N_SECTIONS][6] = {{")
    for i, sec in enumerate(sos):
        b0, b1, b2, _, a1, a2 = sec
        lines.append(
            f"    /* s{i} */ {{"
            f" {b0:+.10e}f, {b1:+.10e}f, {b2:+.10e}f,"
            f" 1.0f, {a1:+.10e}f, {a2:+.10e}f }},"
        )
    lines.append("};")
    return "\n".join(lines)


def main():
    resp_sos  = compute_sos(RESP_BAND,  FS, ORDER)
    heart_sos = compute_sos(HEART_BAND, FS, ORDER)

    n_sections = resp_sos.shape[0]
    assert n_sections == heart_sos.shape[0]

    out = []
    out.append("/* AUTO-GENERATED by scripts/gen_sos_coeffs.py - do not edit manually */")
    out.append(f"/* fs={FS} Hz | order={ORDER} Butterworth bandpass | {n_sections} SOS sections */")
    out.append(f"/* Breathing {RESP_BAND[0]}-{RESP_BAND[1]} Hz  |  Heart {HEART_BAND[0]}-{HEART_BAND[1]} Hz */")
    out.append("")
    out.append("#pragma once")
    out.append("")
    out.append(f"#define SOS_N_SECTIONS  {n_sections}")
    out.append("")
    out.append(fmt_array("g_sos_resp",  f"Breathing {RESP_BAND[0]}-{RESP_BAND[1]} Hz", resp_sos))
    out.append("")
    out.append(fmt_array("g_sos_heart", f"Heart {HEART_BAND[0]}-{HEART_BAND[1]} Hz", heart_sos))
    out.append("")

    text = "\n".join(out)
    if len(sys.argv) > 1:
        with open(sys.argv[1], "w", encoding="ascii", newline="\n") as f:
            f.write(text + "\n")
        sys.stderr.write(f"wrote {sys.argv[1]}\n")
    else:
        print(text)


if __name__ == "__main__":
    main()
